language: java
jdk:
- oraclejdk7
env:
  global:
    secure: IGIsFl6hIqhgrazzWqTaCkRSVf+qrUAds10K9rkkM1cBbqLljTU/H7jYd+akQYRjAQ7GP3xMq5J2/jo/Nf+sqDcRmztIdtO8sx60dJZ4H/aGr7goHDBaaDC9eYw7wUnQi6k5+AS8Tvf2ciDPfoqLpd/3vvST29DplIRJBdM68QQ=
